apiVersion: networking.turnbros.app/v1alpha1
kind: NodePortPassthrough
metadata:
  name: nodeportpassthrough-sample
spec:
  labels:
    fooo-label: asdf
  selector:
    app: MyApp
  annotations: {}
  ports:
  - name: http
    protocol: tcp
  - name: https
    protocol: tcp
  - name: game-udp
    protocol: udp
