apiVersion: networking.turnbros.app/v1alpha1
kind: NodePortPassthrough
metadata:
  name: nodeportpassthrough-sample
  labels:
    foo-label1: bar-value1
  annotations:
    baz-key1: idk-value1
spec:
  unknown_field: "asdf"
  labels:
    foo: bar
  annotations:
    baz: value
  selector:
    app: service-backend1
  ports:
    - name: http
      protocols: ["tcp"]
    - name: https
      protocols: ["tcp"]
    - name: game
      protocols: ["tcp", "udp"]
