apiVersion: networking.turnbros.app/v1alpha1
kind: NodePortPassthrough
metadata:
  name: nodeportpassthrough-sample
spec:
  labels:
    my-label: label-value
  annotations:
    turnbros.app/service-annotation: annotation-value
  selector:
    app: service-backend2
  ports:
    - name: http
      protocols: ["tcp"]
    - name: https
      protocols: ["tcp"]
    - name: game
      protocols: ["tcp", "udp"]
