---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: nodeportpassthroughs.networking.turnbros.app
spec:
  group: networking.turnbros.app
  names:
    kind: NodePortPassthrough
    listKind: NodePortPassthroughList
    plural: nodeportpassthroughs
    singular: nodeportpassthrough
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: NodePortPassthrough is the Schema for the nodeportpassthroughs API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: Spec defines the desired state of NodePortPassthrough
            type: object
            x-kubernetes-preserve-unknown-fields: true
            properties:
              labels:
                description: The labels that will be applied to the service
                type: object
              selector:
                description: The selector that will be applied to the service
                type: object
              annotations:
                description: The annotations that will be applied to the service
                type: object
              ports:
                description: The names and protocols of ports that should be provisioned and mapped
                type: array
                items:
                  type: object
                  required:
                    - name
                    - protocol
                  properties:
                    name:
                      type: string
                    protocol:
                      description: The protocol this port will serve
                      type: string
                      enum:
                        - tcp
                        - TCP
                        - udp
                        - UDP

          status:
            description: Status defines the observed state of NodePortPassthrough
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: true
    subresources:
      status: {}
