---

# Get the configmap the contains the valid port range
# TODO: Find a way to make this dynamic. We shouldn't have to tell the operator what's valid if K8s already knows
- name: Get the config data
  set_fact:
    operator_config_data: "{{ lookup('community.kubernetes.k8s', kind='ConfigMap', resource_name=operator_config, namespace=operator_namespace).data }}"

# Parse the nodeport range start and end, then generate a list of valid port numbers
# Also get a list of all the services in k8s, then use the jmespath query to filter it down to just used nodeports
- name: Parse the config data
  no_log: true
  vars:
    range_extents: "{{ (operator_config_data['controller_manager_config.yaml'] | from_yaml).cluster_nodeport_range }}"
  set_fact:
    cluster_nodeport_range: "{{ range(range_extents.start, range_extents.end + 1) | list }}"
    cluster_service_nodeport_list: "{{ lookup('community.kubernetes.k8s', kind='Service') | json_query(nodeport_query) }}"

# TODO: Add some error handling for when we run out of available ports.
- name: Get a list of available node ports
  no_log: true
  set_fact:
    available_node_ports: "{{ cluster_nodeport_range | difference(cluster_service_nodeport_list) }}"

- name: Get the existing service ports
  when: existing_service != []
  vars:
    existing_service: "{{ lookup('community.kubernetes.k8s', kind='Service', namespace=ansible_operator_meta.namespace, resource_name=ansible_operator_meta.name) }}"
  set_fact:
    existing_service_ports: "{{ existing_service | json_query('spec.ports[]') | from_yaml | default(omit) }}"

- name: Build a list of port objects that includes an available nodePort
  ansible.builtin.set_fact:
    reserved_ports: "{{ reserved_ports + reserved_port }}"
  loop: "{{ ports }}"
  loop_control:
    index_var: idx
  vars:
    reserved_ports: []
    reserved_port:
    - name: "{{ ports[idx].name }}"
      port: "{{ available_node_ports[idx] | int }}"
      nodePort: "{{ available_node_ports[idx] | int }}"
      protocols: "{{ ports[idx].protocols | unique  }}"

- set_fact:
    service_ports: |
      {% for port in reserved_ports %}
      {%- for protocol in port.protocols %}
      {% set port_name='%s-%s'|format(port.name,protocol|lower) %}
      {% set nodeport_query="[? name == '%s'].nodePort"|format(port_name) %}
      {% if existing_service_ports|default(false) %}
      {% set existing_service_nodeport=existing_service_ports|json_query(nodeport_query)|first %}
      {% endif %}
        - name: {{ port_name }}
          nodePort: {{ existing_service_nodeport|default(port.nodePort|int) }}
          port: {{ existing_service_nodeport|default(port.nodePort|int) }}
          protocol: {{ protocol|upper }}
          targetPort: {{ existing_service_nodeport|default(port.nodePort|int) }}
      {% endfor %}
      {% endfor %}

- name: Read definition template file from the Ansible controller file system
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('template', 'service.yml.j2') | from_yaml }}"

